from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib
import matplotlib.pyplot as plt


ScenarioSeries = Dict[str, Dict[int, List[Tuple[float, float]]]]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot MPPT profile measurements (voltage/current) from a CSV log."
    )
    parser.add_argument(
        "--csv",
        type=Path,
        required=True,
        help="CSV generated by b2900_mppt_profile.py",
    )
    parser.add_argument(
        "--scenario",
        action="append",
        dest="scenarios",
        help="Scenario name(s) to plot (default: plot every scenario in the file)",
    )
    parser.add_argument(
        "--channel",
        type=int,
        choices=[1, 2],
        help="Restrict the plot to a single channel (default: plot both)",
    )
    parser.add_argument(
        "--save-dir",
        type=Path,
        help="Directory to write one PNG per scenario (default: show interactively)",
    )
    return parser.parse_args()


def load_series(csv_path: Path) -> ScenarioSeries:
    series: Dict[str, Dict[int, List[Tuple[int, float, float]]]] = defaultdict(
        lambda: defaultdict(list)
    )
    with csv_path.open() as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            scenario = row.get("scenario")
            channel_raw = row.get("channel")
            volts_raw = row.get("ch1_measured_volts") if channel_raw == "1" else row.get(
                "ch2_measured_volts"
            )
            amps_raw = row.get("ch1_measured_amps") if channel_raw == "1" else row.get(
                "ch2_measured_amps"
            )
            step_raw = row.get("step")
            if not scenario or channel_raw is None or volts_raw is None or amps_raw is None:
                continue
            try:
                channel = int(channel_raw)
                volts = float(volts_raw)
                amps = float(amps_raw)
                step = int(step_raw) if step_raw is not None else 0
            except ValueError:
                continue
            series[scenario][channel].append((step, volts, amps))
    sorted_series: ScenarioSeries = {}
    for scenario, channels in series.items():
        sorted_series[scenario] = {}
        for channel, points in channels.items():
            ordered = sorted(points, key=lambda item: item[0])
            sorted_series[scenario][channel] = [(volt, amp) for _, volt, amp in ordered]
    return sorted_series


def plot_series(series: ScenarioSeries, args: argparse.Namespace) -> None:
    if not series:
        raise SystemExit("No data found in CSV")

    scenario_names = sorted(series.keys())
    if args.scenarios:
        scenario_names = [name for name in scenario_names if name in args.scenarios]
    if not scenario_names:
        raise SystemExit("No scenarios matched the selected filters")

    figures: List[Tuple[plt.Figure, str]] = []
    for scenario in scenario_names:
        channels = series[scenario]
        channel_keys = sorted(channels.keys())
        if args.channel is not None:
            channel_keys = [ch for ch in channel_keys if ch == args.channel]
        if not channel_keys:
            continue
        figure, axis = plt.subplots()
        for channel in channel_keys:
            volts = [point[0] for point in channels[channel]]
            amps = [point[1] for point in channels[channel]]
            if not volts:
                continue
            if (channel == 1):
                ch_label = "Solar supply"
            else:
                ch_label = "Battery receive" 
            abs_amps = [abs(value) for value in amps]
            axis.plot(
                volts,
                abs_amps,
                marker="o",
                markersize=3,
                linewidth=0.8,
                label=ch_label,
            )
        axis.set_xlabel("Voltage (V)")
        axis.set_ylabel("Current (A)")
        axis.grid(True, alpha=0.2)
        axis.legend(loc="best")
        axis.set_title(f"{scenario} from {args.csv.name}")
        figure.tight_layout()
        figures.append((figure, scenario))

    if not figures:
        raise SystemExit("No data found after applying channel filters")

    if args.save_dir:
        args.save_dir.mkdir(parents=True, exist_ok=True)
        for figure, scenario in figures:
            safe_name = scenario.replace(" ", "_")
            output_path = args.save_dir / f"{safe_name}.png"
            figure.savefig(output_path, dpi=200)
            print(f"Saved figure to {output_path}")
        return

    backend = matplotlib.get_backend().lower()
    interactive_backends = {
        "gtk3agg",
        "gtk3cairo",
        "macosx",
        "nbagg",
        "qt4agg",
        "qt5agg",
        "qtagg",
        "qtcairo",
        "tkagg",
        "tkcairo",
        "webagg",
        "wx",
        "wxagg",
        "wxcairo",
    }
    if backend not in interactive_backends:
        for figure, scenario in figures:
            safe_name = scenario.replace(" ", "_")
            fallback_path = args.csv.with_name(f"{args.csv.stem}_{safe_name}.png")
            figure.savefig(fallback_path, dpi=200)
            print(
                f"Backend '{backend}' cannot show figures; saved plot to {fallback_path}"
            )
        return

    plt.show()


def main() -> None:
    args = parse_args()
    if not args.csv.exists():
        raise SystemExit(f"CSV file not found: {args.csv}")
    series = load_series(args.csv)
    plot_series(series, args)


if __name__ == "__main__":
    main()
