from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Dict, List

import matplotlib
import matplotlib.pyplot as plt


SweepData = Dict[int, Dict[str, List[float]]]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot logged solar sweep curves from a CSV file."
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=Path("solar_sweep_log.csv"),
        help="CSV generated by log_solar_sweep.py (default: solar_sweep_log.csv)",
    )
    parser.add_argument(
        "--max-sweeps",
        type=int,
        help="Limit the number of sweeps shown (default: plot all sweeps)",
    )
    parser.add_argument(
        "--set",
        dest="sets",
        type=int,
        action="append",
        help=(
            "Plot only the specified set(s) of 86 points. "
            "Each set corresponds to a sweep index from the CSV."
        ),
    )
    parser.add_argument("--voltage-min", type=float, help="Drop points below this voltage")
    parser.add_argument("--voltage-max", type=float, help="Drop points above this voltage")
    parser.add_argument("--current-min", type=float, help="Drop points below this current")
    parser.add_argument("--current-max", type=float, help="Drop points above this current")
    parser.add_argument(
        "--save",
        type=Path,
        help="Optional path to save the figure instead of showing it on-screen",
    )
    parser.add_argument(
        "--title",
        type=str,
        help="Optional chart title (defaults to file name and sweep count)",
    )
    return parser.parse_args()


def load_sweeps(csv_path: Path) -> SweepData:
    sweeps: SweepData = defaultdict(lambda: {"volts": [], "amps": []})
    with csv_path.open() as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            try:
                sweep_idx = int(row["sweep"])
                volts = float(row["volts"])
                amps = float(row["amps"])
            except (KeyError, ValueError):
                continue
            sweep = sweeps[sweep_idx]
            sweep["volts"].append(volts)
            sweep["amps"].append(amps)
    return dict(sweeps)


def filter_points(
    volts: List[float], amps: List[float], args: argparse.Namespace
) -> tuple[List[float], List[float]]:
    filtered_v: List[float] = []
    filtered_a: List[float] = []
    for v, a in zip(volts, amps):
        if args.voltage_min is not None and v < args.voltage_min:
            continue
        if args.voltage_max is not None and v > args.voltage_max:
            continue
        if args.current_min is not None and a < args.current_min:
            continue
        if args.current_max is not None and a > args.current_max:
            continue
        filtered_v.append(v)
        filtered_a.append(a)
    return filtered_v, filtered_a


def plot_sweeps(sweeps: SweepData, args: argparse.Namespace) -> None:
    if not sweeps:
        raise SystemExit("No sweep data found in CSV")

    figure, axis = plt.subplots()
    sorted_indices = sorted(sweeps.keys())
    if args.sets:
        missing = [s for s in args.sets if s not in sweeps]
        if missing:
            raise SystemExit(f"Requested set(s) not found in file: {missing}")
        sorted_indices = sorted(args.sets)
    elif args.max_sweeps is not None:
        sorted_indices = sorted_indices[: args.max_sweeps]

    for sweep_idx in sorted_indices:
        sweep = sweeps[sweep_idx]
        volts, amps = filter_points(sweep["volts"], sweep["amps"], args)
        if not volts:
            print(f"Sweep {sweep_idx} skipped (no points within selected ranges)")
            continue
        axis.plot(
            volts,
            amps,
            marker="o",
            markersize=3,
            linewidth=0.8,
            label=f"Sweep {sweep_idx}",
        )

    axis.set_xlabel("Voltage (V)")
    axis.set_ylabel("Current (A)")
    axis.grid(True, alpha=0.2)
    axis.legend(loc="best")
    title = args.title or f"{len(sorted_indices)} sweeps from {args.csv.name}"
    axis.set_title(title)
    figure.tight_layout()

    if args.save:
        figure.savefig(args.save, dpi=200)
        print(f"Saved figure to {args.save}")
        return

    backend = matplotlib.get_backend().lower()
    interactive_backends = {
        "gtk3agg",
        "gtk3cairo",
        "macosx",
        "nbagg",
        "qt4agg",
        "qt5agg",
        "qtagg",
        "qtcairo",
        "tkagg",
        "tkcairo",
        "webagg",
        "wx",
        "wxagg",
        "wxcairo",
    }
    if backend not in interactive_backends:
        fallback_path = args.csv.with_suffix(".png")
        figure.savefig(fallback_path, dpi=200)
        print(
            f"Backend '{backend}' cannot show figures; saved plot to {fallback_path}"
        )
        return

    plt.show()


def main() -> None:
    args = parse_args()
    if not args.csv.exists():
        raise SystemExit(f"CSV file not found: {args.csv}")
    sweeps = load_sweeps(args.csv)
    plot_sweeps(sweeps, args)


if __name__ == "__main__":
    main()
